
CREATE TABLE IF NOT EXISTS emails (
id SERIAL PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS phone_numbers (
id SERIAL PRIMARY KEY,
phone VARCHAR (20) NOT NULL UNIQUE
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'postgres') THEN
        CREATE ROLE postgres WITH REPLICATION LOGIN PASSWORD '123123';
    ELSE
        ALTER ROLE postgres WITH REPLICATION LOGIN PASSWORD '123123';
    END IF;
END $$;
